<?php

$diagnosedIllness = [
	  'Schizophrenia',
      'Schizoaffective Disorder',
      'Bipolar I Disorder',
      'Bipolar II Disorder',
      'Cyclothymic Disorder',
      'Substance/Medication-Induced Bipolar Related Disorder',
      'Other Specified Bipolar and Related Disorder',
      'Unspecified Bipolar and Related Disorder',
      'Disruptive Mood Dysregulation Disorder',
      'Major Depressive Disorder, Single and Recurrent Episodes',
      'Persistent Depressive Disorder AKA Dysthymia',
      'Premenstrual Dysphoric Disorder',
      'Substance/Medication-Induced Depressive Disorder',
      'Depressive Disorder Due to Another Medical Condition',
      'Other Specified Depressive Disorder',
      'Unspecified Depressive Disorder',
      'Generallized Axiety Disorder',
      'Substance/Medication-Induced Anxiety Disorder',
      'Anxiety Disorder due to another Medical Condition',
      'Other Specified Anxiety Disorder',
      'Obsessive-Compulsive Disorder',
      'Body Dismorphic Disorder',
      'Hoarding Disorder',
      'Excoriation Disorder/Skin-Picking',
      'Substance/Medication-Induced Obsessive-Compulsive and Related Disorder',
      'Other Specified Obsessive-Compulsive and Related Disorder',
      'Unspecified Obsessive-Compulsive and Related Disorder',
      'Reactive Attachment Disorder',
      'Disinhibited Social Engagement Disorder',
      'Posttraumatic Stress disorder',
      'PTSD',
      'Acute Stress Disorder',
      'Adjustment Disorders',
      'Other Specified Trauma-and Stressor-Related Disorder',
      'Unspecified Trauma-and Stressor-Related Disorder'];

$compareDiagnosis = [
	  'Schizophrenia2',
      'Schizoaffective Disorder',
      'Bipolar I Disorder',
      'Bipolar II Disorder',
      'Cyclothymic Disorder',
      'Substance/Medication-Induced Bipolar and Related Disorder',
      'Other Specified Bipolar and Related Disorder',
      'Unspecified Bipolar and Related Disorder',
      'Disruptive Mood Dysregulation Disorder',
      'Major Depressive Disorder, Single and Recurrent Episodes',
      'Persistent Depressive Disorder AKA Dysthymia',
      'Premenstrual Dysphoric Disorder',
      'Substance/Medication-Induced Depressive Disorder',
      'Depressive Disorder Due to Another Medical Condition',
      'Other Specified Depressive Disorder',
      'Unspecified Depressive Disorder',
      'Generallized Axiety Disorder',
      'Substance/Medication-Induced Anxiety Disorder',
      'Anxiety Disorder due to another Medical Condition',
      'Other Specified Anxiety Disorder',
      'Obsessive-Compulsive Disorder',
      'Body Dismorphic Disorder',
      'Hoarding Disorder',
      'Excoriation Disorder/Skin-Picking',
      'Substance/Medication-Induced Obsessive-Compulsive and Related Disorder',
      'Other Specified Obsessive-Compulsive and Related Disorder',
      'Unspecified Obsessive-Compulsive and Related Disorder',
      'Reactive Attachment Disorder',
      'Disinhibited Social Engagement Disorder',
      'Posttraumatic Stress disorder',
      'PTSD',
      'Acute Stress Disorder',
      'Adjustment Disorders',
      'Other Specified Trauma-and Stressor-Related Disorder',
      'Unspecified Trauma-and Stressor-Related Disorder'];
